In [1]:
import numpy as np

##### creating arrays using array, arange, linspace

In [2]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3=np.arange(0,20,3) #start at 0 end before 20 add 3 everytime
arr3

array([ 0,  3,  6,  9, 12, 15, 18])

In [5]:
arr4=np.linspace(0,9,10) #starts at 0 end at 9 in total 10 numbers
arr4

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### finding dimension and reshape and resize

In [6]:
arr2.shape #finds dimension

(2, 3)

In [8]:
arr2.reshape(3,2) #does not change original array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2.resize(3,2)#changes original array
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

#### creating ones and zeros ,eye,diag

In [24]:
np.ones((3,4),int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.diag(arr2) #it extracts diagonal elements of specified array

array([1, 4])

#### creating array with repeated list vs creating array with repeated elements

In [20]:
np.array([1,2,3]*4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [21]:
np.repeat([1,2,3],4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

#### combining arrays

In [27]:
np.vstack((arr1,2*arr1))

array([[1, 2, 3],
       [2, 4, 6]])

In [29]:
np.hstack((arr1,2*arr1))

array([1, 2, 3, 2, 4, 6])

#### operations

In [34]:
print(arr1 + (2*arr1)) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(arr1-(2*arr1))  # elementwise subtraction [1 2 3] - [4 5 6] = [-3 -3 -3]
print(arr1 * (2*arr1)) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(arr1 / (2*arr1)) # elementwise divison   [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print(arr1**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[3 6 9]
[-1 -2 -3]
[ 2  8 18]
[0.5 0.5 0.5]
[1 4 9]


#### dot,tranpose 

In [35]:
arr1.dot(arr2)

array([22, 28])

In [43]:
arr1.T

array([1, 2, 3])

In [42]:
arr1

array([1, 2, 3])

In [38]:
arr1.shape

(3,)

In [39]:
arr1.T.shape

(3,)

In [40]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
arr2.T

array([[1, 3, 5],
       [2, 4, 6]])

In [48]:
arr1.reshape((3,1))

array([[1],
       [2],
       [3]])

In [49]:
a=arr1.astype('f')

In [50]:
a

array([1., 2., 3.], dtype=float32)

In [51]:
x=arr1

#### math functions

In [52]:
x.sum()

6

In [53]:
x.max()

3

In [54]:
x.min()

1

In [55]:
x.mean()

2.0

In [56]:
x.std()

0.816496580927726

In [57]:
x.argmax()  #returns index

2

In [58]:
x.argmin()

0

#### indexing,slicing for one dimensinal array

In [59]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

In [60]:
s[0], s[4], s[-1]

(0, 16, 144)

In [61]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

In [62]:
#Use negatives to count from the back.
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [63]:
#array[start:stop:stepsize]
s[-5:-10:-2]

array([64, 36, 16], dtype=int32)

#### index,slice for multi dim array

In [64]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [65]:
r[2, 2]

14

In [66]:
r[3, 3:6]

array([21, 22, 23])

In [68]:
r[:2, -4:-2]

array([[2, 3],
       [8, 9]])

In [69]:
r[1]

array([ 6,  7,  8,  9, 10, 11])

In [70]:
r[-1, ::2]

array([30, 32, 34])

In [71]:
r[r > 30] = 30

In [72]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### copy and modify array

In [81]:
r1=r[3] #change in r1 changes r
r1

array([0, 0, 0, 0, 0, 0])

In [78]:
r1[:]= 0

In [79]:
r1

array([0, 0, 0, 0, 0, 0])

In [80]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  0,  0,  0,  0,  0],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [82]:
#copy of r
r2=r[3].copy()
r2[:]=18


In [83]:
r2

array([18, 18, 18, 18, 18, 18])

In [84]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  0,  0,  0,  0,  0],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

### iterating over arrays

In [85]:
#creating a random 4,3 array
b=np.arange(0,12,1)
b.resize(4,3)
b


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [86]:
#another method
c=np.random.randint(0,12,(4,3))
c

array([[ 7,  3,  2],
       [ 5,  8, 11],
       [ 6, 10,  9],
       [ 2,  3,  2]])

In [87]:
len(c)

4

In [90]:
enumerate(c)


In [91]:
for row in c:
    print(row)

[7 3 2]
[ 5  8 11]
[ 6 10  9]
[2 3 2]


In [93]:
for i in range(len(c)):
    print(c[i])

[7 3 2]
[ 5  8 11]
[ 6 10  9]
[2 3 2]


In [94]:
for i,row in enumerate(c):
    print('row',i,'is',row)

row 0 is [7 3 2]
row 1 is [ 5  8 11]
row 2 is [ 6 10  9]
row 3 is [2 3 2]


In [95]:
c1=c*2
c1

array([[14,  6,  4],
       [10, 16, 22],
       [12, 20, 18],
       [ 4,  6,  4]])

In [96]:
zip(c,c1)

In [97]:
for i,j in zip(c,c1):
    print(i,'*',j,'=',i*j)

[7 3 2] * [14  6  4] = [98 18  8]
[ 5  8 11] * [10 16 22] = [ 50 128 242]
[ 6 10  9] * [12 20 18] = [ 72 200 162]
[2 3 2] * [4 6 4] = [ 8 18  8]
